# Generated by Django 3.1.6 on 2022-02-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='NFT Name')),
                ('serial_date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Aprroved')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aapp.user')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.serial')),
            ],
        ),
    ]
